"""add user auth tables

Revision ID: 69941843136f
Revises: 163d675a5e9d
Create Date: 2025-06-22 23:01:21.946626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69941843136f'
down_revision: Union[str, None] = '163d675a5e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_artists_boardgameartist_id'), table_name='artists')
    op.drop_index(op.f('idx_artists_game_id'), table_name='artists')
    op.drop_index(op.f('idx_categories_boardgamecategory_id'), table_name='categories')
    op.drop_index(op.f('idx_categories_game_id'), table_name='categories')
    op.drop_index(op.f('idx_designers_boardgamedesigner_id'), table_name='designers')
    op.drop_index(op.f('idx_designers_game_id'), table_name='designers')
    op.drop_index(op.f('idx_games_abstracts_rank'), table_name='games')
    op.drop_index(op.f('idx_games_average'), table_name='games')
    op.drop_index(op.f('idx_games_average_weight'), table_name='games')
    op.drop_index(op.f('idx_games_cgs_rank'), table_name='games')
    op.drop_index(op.f('idx_games_childrens_games_rank'), table_name='games')
    op.drop_index(op.f('idx_games_family_games_rank'), table_name='games')
    op.drop_index(op.f('idx_games_max_players'), table_name='games')
    op.drop_index(op.f('idx_games_min_players'), table_name='games')
    op.drop_index(op.f('idx_games_name'), table_name='games')
    op.drop_index(op.f('idx_games_party_games_rank'), table_name='games')
    op.drop_index(op.f('idx_games_rank'), table_name='games')
    op.drop_index(op.f('idx_games_strategy_games_rank'), table_name='games')
    op.drop_index(op.f('idx_games_thematic_rank'), table_name='games')
    op.drop_index(op.f('idx_games_wargames_rank'), table_name='games')
    op.drop_index(op.f('idx_games_year_published'), table_name='games')
    op.drop_index(op.f('idx_mechanics_boardgamemechanic_id'), table_name='mechanics')
    op.drop_index(op.f('idx_mechanics_game_id'), table_name='mechanics')
    op.drop_index(op.f('idx_pax_games_bgg_id'), table_name='pax_games')
    op.drop_index(op.f('idx_suggested_players_game_id'), table_name='suggested_players')
    op.drop_index(op.f('idx_suggested_players_player_count'), table_name='suggested_players')
    op.drop_index(op.f('idx_suggested_players_recommendation_level'), table_name='suggested_players')
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('hashed_password', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_admin', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_suggested_players_recommendation_level'), 'suggested_players', ['recommendation_level'], unique=False)
    op.create_index(op.f('idx_suggested_players_player_count'), 'suggested_players', ['player_count'], unique=False)
    op.create_index(op.f('idx_suggested_players_game_id'), 'suggested_players', ['game_id'], unique=False)
    op.create_index(op.f('idx_pax_games_bgg_id'), 'pax_games', ['bgg_id'], unique=False)
    op.create_index(op.f('idx_mechanics_game_id'), 'mechanics', ['game_id'], unique=False)
    op.create_index(op.f('idx_mechanics_boardgamemechanic_id'), 'mechanics', ['boardgamemechanic_id'], unique=False)
    op.create_index(op.f('idx_games_year_published'), 'games', ['year_published'], unique=False)
    op.create_index(op.f('idx_games_wargames_rank'), 'games', ['wargames_rank'], unique=False)
    op.create_index(op.f('idx_games_thematic_rank'), 'games', ['thematic_rank'], unique=False)
    op.create_index(op.f('idx_games_strategy_games_rank'), 'games', ['strategy_games_rank'], unique=False)
    op.create_index(op.f('idx_games_rank'), 'games', ['rank'], unique=False)
    op.create_index(op.f('idx_games_party_games_rank'), 'games', ['party_games_rank'], unique=False)
    op.create_index(op.f('idx_games_name'), 'games', ['name'], unique=False)
    op.create_index(op.f('idx_games_min_players'), 'games', ['min_players'], unique=False)
    op.create_index(op.f('idx_games_max_players'), 'games', ['max_players'], unique=False)
    op.create_index(op.f('idx_games_family_games_rank'), 'games', ['family_games_rank'], unique=False)
    op.create_index(op.f('idx_games_childrens_games_rank'), 'games', ['childrens_games_rank'], unique=False)
    op.create_index(op.f('idx_games_cgs_rank'), 'games', ['cgs_rank'], unique=False)
    op.create_index(op.f('idx_games_average_weight'), 'games', ['average_weight'], unique=False)
    op.create_index(op.f('idx_games_average'), 'games', ['average'], unique=False)
    op.create_index(op.f('idx_games_abstracts_rank'), 'games', ['abstracts_rank'], unique=False)
    op.create_index(op.f('idx_designers_game_id'), 'designers', ['game_id'], unique=False)
    op.create_index(op.f('idx_designers_boardgamedesigner_id'), 'designers', ['boardgamedesigner_id'], unique=False)
    op.create_index(op.f('idx_categories_game_id'), 'categories', ['game_id'], unique=False)
    op.create_index(op.f('idx_categories_boardgamecategory_id'), 'categories', ['boardgamecategory_id'], unique=False)
    op.create_index(op.f('idx_artists_game_id'), 'artists', ['game_id'], unique=False)
    op.create_index(op.f('idx_artists_boardgameartist_id'), 'artists', ['boardgameartist_id'], unique=False)
    # ### end Alembic commands ###
