"""rename recommendation to recommendation_level

Revision ID: d258c28b421e
Revises: 
Create Date: 2025-06-08 21:16:26.277120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd258c28b421e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggested_players', sa.Column('recommendation_level', sa.String(), nullable=True))
    op.drop_column('suggested_players', 'recommendation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggested_players', sa.Column('recommendation', sa.VARCHAR(), nullable=True))
    op.drop_column('suggested_players', 'recommendation_level')
    # ### end Alembic commands ###
